### ISSUE TITLE
Plugin doesn't find gmp plugin even though php7.3-gmp package is installed

### ISSUE THREAD

**Issue by belidzs** [yrccondor/wp-webauthn#11]
I have both `php7.3-gmp` and `php7.3-mbstring` installed on my Ubuntu system but it seems that wp-webauthn is unable to use it. Is this version supported at all?

Logs are here: https://hastebin.com/zecikapabe.md

**Comment by yrccondor** [comment]
It looks like your PHP didn't find your `gmp` extension. Remember to enable the plugin in your `php.ini` and reload your PHP. Then you can check `phpinfo()` to make sure `gmp` is installed.

https://stackoverflow.com/questions/40010197/how-to-install-gmp-for-php7-on-ubuntu

**Comment by belidzs** [comment]
The issue was on my side, I was checking the presence of this plugin on a different server than the one actually served the site. Thanks and sorry for the noise
