### ISSUE TITLE
The REST API encountered an error

### ISSUE THREAD

**Issue by vwt12eh8** [yrccondor/wp-webauthn#12]
If you check Site Health while this plugin is enabled, the following error will occur.

## The REST API encountered an error
> The REST API is one way WordPress, and other applications, communicate with the server. One example is the block editor screen, which relies on this to display, and save, your posts and pages.
> 
>The REST API request failed due to an error.
>Error: cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received (http_request_failed)

## Your site could not complete a loopback request
> Loopback requests are used to run scheduled events, and are also used by the built-in editors for themes and plugins to verify code stability.
> 
> The loopback request to your site failed, this means features relying on them are not currently working as expected.
> Error: cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received (http_request_failed)

Disabling the plugin will eliminate this error.

For reference, the environment of the server where the problem occurs is as follows.

```
### wp-core ###

version: 5.4.2
site_language: ja
user_language: en_US
timezone: Asia/Tokyo
https_status: true
user_registration: 1
default_comment_status: open
multisite: false
dotorg_communication: true

### wp-server ###

server_architecture: Linux 4.2.8 armv7l
httpd_software: Apache/2.4.29
php_version: 7.4.9
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: 60
upload_max_size: 128M
php_post_max_size: 128M
curl_version: 7.58.0 OpenSSL/1.1.1g
suhosin: false
imagick_availability: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.5.57-MariaDB
client_version: mysqlnd 7.4.9

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /var/www/html/wp-content
WP_PLUGIN_DIR: /var/www/html/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
```

**Comment by yrccondor** [comment]
Hi,
the problem is, `session` is limited in WordPress but it is a necessary PHP feature for this plugin.
I've did a quick fix and you will be able to update the plugin soon. This should fix the problems.

**Comment by vwt12eh8** [comment]
I made a similar change to https://github.com/yrccondor/wp-webauthn/commit/1acb274607caef25ef714afc279a52872a6bf303 from the Plugin Editor and confirmed that the problem was resolved.
Thank you for your prompt response.
