### ISSUE TITLE
Bug:  Found js error，can not login for admin

### ISSUE THREAD

**Issue by liushooter** [yrccondor/wp-webauthn#13]
My wp version: 5.2.4，installed the plugin，the admin login page is following:

> <img src="https://user-images.githubusercontent.com/1235106/90304400-d3c6f880-dee9-11ea-8c35-91e5660142e6.jpg" width="350">

## js error
> <img src="https://user-images.githubusercontent.com/1235106/90304496-15a46e80-deeb-11ea-9b59-d4991dd26a30.png" width="300">

> <img src="https://user-images.githubusercontent.com/1235106/90304497-1806c880-deeb-11ea-9f57-16811400a242.png" width="300">

**Comment by yrccondor** [comment]
Hi,
WP-WebAuthn works well on the original login page. It seems like other plugin or theme have modified the login page. Do you have any other login plugin installed? Maybe I can make WP-WebAuthn compatible with it.

**Comment by liushooter** [comment]
https://github.com/yrccondor/wp-webauthn/blob/1.0.15/js/login.js#L191

I guess the plugin not compatible with < 5.5

>![](https://user-images.githubusercontent.com/1235106/90308434-0edd2200-df12-11ea-9530-49a04f26fa54.png)

>![](https://user-images.githubusercontent.com/1235106/90308437-113f7c00-df12-11ea-827f-518917f0be03.jpg)

>![](https://user-images.githubusercontent.com/1235106/90308441-14d30300-df12-11ea-8b9f-859b91f6795f.png)

**Comment by yrccondor** [comment]
I couldn't reproduce this issue on WordPress 5.5. Could you please list your installed plugins if it is possible?

**Comment by liushooter** [comment]
插件支持WordPress 5.5 没有问题
我的wp是5.2，admin login的页面结构不一样了
`document.querySelectorAll("#loginform label")[0].innerText = php_vars.i18n_9` 会直接破坏页面结构
