### ISSUE TITLE
关于检测HTTPS

### ISSUE THREAD

**Issue by Mas0nShi** [yrccondor/wp-webauthn#17]
部署时
报错如下
> 你的站点似乎没有运行在安全上下文中，这会导致 WebAuthn 无法使用。请确保你的站点在使用 HTTPS 连接或处于 localhost 中。

然而事实上我开启了HTTPS，这就很疑惑，翻看了一下插件的代码
最终发现问题在于检测点 `$_SERVER['HTTPS'] = 'on';`
而我设置的是 `$_SERVER['HTTPS'] = 'ON';`大小写问题导致了插件误报
关于此，也许是我单方面设置的问题

提交下，就当作为后来的人避免走一段弯路叭

**Comment by yrccondor** [comment]
已于 6168945 修复

**Comment by Zxilly** [comment]
@yrccondor 请问这个什么时候能release呢

**Comment by yrccondor** [comment]
@Zxilly 正在等待其他贡献者更新翻译，会在几天内发布更新

**Comment by yrccondor** [comment]
1.2.4 已发布
