### ISSUE TITLE
Login window looks a bit strange with wrapped text

### ISSUE THREAD

**Issue by niiconn** [yrccondor/wp-webauthn#24]
The login window looks a bit strange in german translation with wrapped around text overlapping the buttons. 

![webauthn-screenshot](https://user-images.githubusercontent.com/3883135/130595050-f3723e91-3ce1-4a5a-aa6d-6955b35bd677.png)

**Comment by niiconn** [comment]
Also, in the normal login form the button to change to webauthn is also wrapping around the 'keep logged in' checkbox label and the login button (also because of german translation?)

![webauthn-screenshot-2](https://user-images.githubusercontent.com/3883135/130595557-5eb9014b-128b-4831-a180-46c97d643cf7.png)

**Comment by yrccondor** [comment]
i'll fix these style problems in the next version

**Comment by yrccondor** [comment]
All fixed in e6531a2. Sorry for the delay.

![2022-01-09_02-00-47](https://user-images.githubusercontent.com/14820835/148666309-58dd0200-8e20-4397-9452-2510a7b96a83.png)
