### ISSUE TITLE
安全密钥丢失后如何登录

### ISSUE THREAD

**Issue by liups233** [yrccondor/wp-webauthn#30]
我最近不小心丢了yubikey，账号设置了只能用安全密钥登录，不知道如何修改文件才能取消

目前用的是宝塔面板，能否直接删除插件目录呢

PS. 在上学，也许不能及时回复

**Comment by yrccondor** [comment]
删除插件文件并删除数据库中 `wp_options` 表中所有以 `wwa_` 开头的键值即可。

**Comment by liups233** [comment]
谢谢，已解决
