### ISSUE TITLE
Not allowed to view settings page as admin

### ISSUE THREAD

**Issue by spaetz** [yrccondor/wp-webauthn#36]
Hi, running wp-webauthn 1.2.6 just fine. However, when I try to visit: wp-admin/options-general.php?page=wwa_admin I get `Sorry, you are not allowed to access this page.`

I AM logged in as Administrator and using the PublishPress Capabilities plugin I have verified that my user has the `edit_plugins` capability just fine. Is there anything I have been overlooking?

**Comment by yrccondor** [comment]
if you have `edit_plugins` permission it should work. this plugin uses wordpress built-in APIs only so I have no idea about this problem for now. I'll check the PublishPress Capabilities plugin to see if it modifies wordpress' capability system.

**Comment by spaetz** [comment]
The issue ocurred before I had the PublishPress thingie installed. I only installed it to inspect and modify capabilities. I will investigate further to see if I can find a reason.

**Comment by scorpido74** [comment]
Having the same problems here.  @spaetz did you ever find the solution ?

**Comment by spaetz** [comment]
Nope, still not able to view the settings page...

**Comment by yrccondor** [comment]
With some investigation could you please provide a list of installed plugins if possible? I noticed some plugins may modify the capability system but I'm not quite sure. Haven't seen this kind of reports before.

**Comment by yrccondor** [comment]
Btw, could you please check the permission of the plugin files and also your PHP version? These shouldn't be problems if you install from wordpress plugin catalog within admin panel

**Comment by spaetz** [comment]
PHP version | 8.1.5

Hi, these are the plugins I have installed. They were all installed using the plugin catalog:

ActivityPub Version 0.13.3 
Autoptimize | Version 3.0.4 
Disable XML-RPC| 	Version 1.0.1
FooBox Image Lightbox Version 2.7.17 
FooGallery	Version 2.2.7 
Limit Login Attempts Reloaded Version 2.25.3 
OMGF		Version 5.1.3
WP-WebAuthn Version 1.2.6

I also have this one installed in order to manipulate permissions, but I only installed it AFTER webauthn did not work as expected for the admin, so it should not be guilty:
PublishPress Capabilities Version 2.4.1 \| By PublishPress

**Comment by yrccondor** [comment]
thanks to #37, could you please check whether the problem exists in version 1.2.7?

**Comment by spaetz** [comment]
Yes, that was it!
1) I do have the "edit files online" feature disabled
2) The settings page now shows a page saying:
  >   To register a new authenticator or edit your authenticators, please go to your profile.

Thanks for webauthn! Let me know if I can donate some money to you (otherwise I'll donate it to some charity) as a token of gratitude.

**Comment by yrccondor** [comment]
> The settings page now shows a page saying: To register a new authenticator or edit your authenticators, please go to your profile.

Sorry just realized some options are hidden due to the same reason - have fixed it and please enjoy version 1.2.8. Now you can access the whole settings page of this plugin.

> Let me know if I can donate some money to you (otherwise I'll donate it to some charity)

Many thanks and please donate it to any charity you like if possible. Sorry it took a long time to fix the problem.
