### ISSUE TITLE
New passkey feature

### ISSUE THREAD

**Issue by dishangti** [yrccondor/wp-webauthn#49]
Android, Windows, Mac OS and iOS now support passkey, which allows users to generate and store keys by software  , but use the key by biometric or screen lock. This helps to synchronize keys between devices.
But I can only use the feature on my iPad with iPad OS 16.3. On my pixel7 with android 13, I can't generate passkey but build-in security key.

**Comment by yrccondor** [comment]
i believe it is compatible with android 13: just enable usernameless login feature

![Screenshot_20230206-152928](https://user-images.githubusercontent.com/14820835/217015295-a41d4d6c-678b-49e8-95ba-46a0b260cf52.jpg)

**Comment by dishangti** [comment]
Thanks very much for pointing it out❤️

**Comment by dishangti** [comment]
Emmm, but when I usde usernameless feature, it show
