### ISSUE TITLE
Vivaldi browser and Bitwarden

### ISSUE THREAD

**Issue by BackSeat** [yrccondor/wp-webauthn#60]
Webauthn has been in use for a number of years and works well. I recently changed from Brave browser to Vivaldi, both Chrom(e|ium) based.

When I try to authenticate via webauthn I now get a Bitwarden popup that says, "No passkeys found for this application."

I'm not sure whether this is a Vivaldi problem, a Bitwarden problem or a webauthn problem. Using a different browser fixes it; disabling the Bitwarden plugin fixes it.

I'd welcome any suggestions to help pin down the cause (and to fix it).

**Comment by yrccondor** [comment]
Hi BackSeat,

Thanks for reporting this. With some searching I believe that's Bitwarden's new "feature": https://github.com/bitwarden/clients/issues/6824 let me know if things still not working after they resolve this problem :-)

**Comment by BackSeat** [comment]
Thank you, that's exactly the problem, and I suspect they've released an update as I no longer have the problem. Appreciate your help, thanks.
