### ISSUE TITLE
Rename variable $user_info to $user

### ISSUE THREAD

**Issue by bfren** [yrccondor/wp-webauthn#70]
Great plugin, love it, working perfectly except I am getting the following PHP warnings in my logs:

```
FastCGI sent in stderr: "PHP message: PHP Warning:  Undefined variable $user_info in wp-content/plugins/wp-webauthn/wwa-ajax.php on line 1014" while reading response header from upstream, client: 172.18.0.5, server: , request: "POST /wp-admin/admin-ajax.php?action=wwa_auth HTTP/1.0", upstream: "fastcgi://127.0.0.1:9000", host: "xxxxx", referrer: "https://xxxxx/wp-login.php?loggedout=true&wp_lang=en_GB"
```

I wonder, should the following line be `if($user == false)`?

https://github.com/yrccondor/wp-webauthn/blob/7ba904e1020a15ea593301b05ecfc4d74aa61570/wwa-ajax.php#L1014

**Comment by yrccondor** [comment]
Hi bfren,
Thank you for reporting this issue! Yes, you are right - sorry for this error and i'll fix this later today :-)

**Comment by yrccondor** [comment]
That would be great, thank you!
